// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[filename].tsx";
import * as $1 from "./routes/_404.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/_middleware.ts";
import * as $4 from "./routes/api/joke.ts";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/notes/[slug].tsx";
import * as $7 from "./routes/notes/index.tsx";
import * as $8 from "./routes/places/[slug].tsx";
import * as $9 from "./routes/places/index.tsx";
import * as $10 from "./routes/places/trans-america-trail/[slug].tsx";
import * as $11 from "./routes/places/trans-america-trail/index.tsx";

const manifest = {
  routes: {
    "./routes/[filename].tsx": $0,
    "./routes/_404.tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/_middleware.ts": $3,
    "./routes/api/joke.ts": $4,
    "./routes/index.tsx": $5,
    "./routes/notes/[slug].tsx": $6,
    "./routes/notes/index.tsx": $7,
    "./routes/places/[slug].tsx": $8,
    "./routes/places/index.tsx": $9,
    "./routes/places/trans-america-trail/[slug].tsx": $10,
    "./routes/places/trans-america-trail/index.tsx": $11,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
