// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/_404.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/_middleware.ts";
import * as $4 from "./routes/api/joke.ts";
import * as $5 from "./routes/future.tsx";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/library.tsx";
import * as $8 from "./routes/notes/[slug].tsx";
import * as $9 from "./routes/notes/index.tsx";
import * as $10 from "./routes/now.tsx";
import * as $11 from "./routes/places/[slug].tsx";
import * as $12 from "./routes/places/index.tsx";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/_404.tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/_middleware.ts": $3,
    "./routes/api/joke.ts": $4,
    "./routes/future.tsx": $5,
    "./routes/index.tsx": $6,
    "./routes/library.tsx": $7,
    "./routes/notes/[slug].tsx": $8,
    "./routes/notes/index.tsx": $9,
    "./routes/now.tsx": $10,
    "./routes/places/[slug].tsx": $11,
    "./routes/places/index.tsx": $12,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
